# Generated by Django 5.1.2 on 2024-10-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('zip_code', models.CharField(max_length=30, verbose_name='Zip Code')),
                ('street', models.CharField(max_length=30, verbose_name='Street')),
                ('house_number', models.CharField(max_length=30, verbose_name='House Number')),
            ],
        ),
        migrations.CreateModel(
            name='DecorationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Decoration type')),
            ],
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('remaining', models.IntegerField(default=0, verbose_name='Remaining')),
                ('price', models.DecimalField(decimal_places=2, default=1.99, max_digits=10, verbose_name='Price')),
                ('flower_img', models.ImageField(upload_to='flowers/')),
                ('bouquets_img', models.ImageField(upload_to='bouquets/')),
            ],
        ),
        migrations.CreateModel(
            name='WrappingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('remaining', models.FloatField(default=0, verbose_name='Remaining')),
                ('price', models.DecimalField(decimal_places=2, default=0.25, max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=40, verbose_name='Last Name')),
                ('client_phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
            ],
        ),
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('image', models.ImageField(upload_to='decorations/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.decorationtype', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roses_qty', models.IntegerField(default=0, verbose_name='Roses Quantity')),
                ('decoration_qty', models.IntegerField(default=0, verbose_name='Decorations Quantity')),
                ('wp_qty', models.IntegerField(default=0, verbose_name='Wrapping Paper Quantity')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.client')),
                ('decoration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.decorations')),
                ('roses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.flowers')),
                ('wrappingpaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.wrappingpaper')),
            ],
        ),
    ]
