# Generated by Django 5.1.2 on 2024-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_materials_remove_order_wrappingpaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowers',
            name='price',
            field=models.FloatField(default=1.99, verbose_name='Price'),
        ),
    ]
