# Generated by Django 5.1.2 on 2024-10-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_name_decorationtype_decoration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorations',
            name='name',
        ),
    ]
