# Generated by Django 5.1.2 on 2024-10-21 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_decorationtype_prduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorationtype',
            name='prduct_image',
        ),
    ]
