# Generated by Django 5.1.2 on 2024-10-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_prduct_image_decorationtype_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decorations',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
    ]
