# Generated by Django 5.1.2 on 2024-10-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_decorations_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='delivery_option',
            field=models.CharField(default=2, max_length=30, verbose_name='Pristaytas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Miestas'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=30, verbose_name='Namo numeris'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Gatvė'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=30, verbose_name='Pašto kodas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone_number',
            field=models.CharField(max_length=30, verbose_name='Telefono numeris'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='El. Paštas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Pavardė'),
        ),
    ]
