# Generated by Django 5.1.2 on 2024-10-22 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_client_delivery_option_alter_address_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_option', models.CharField(max_length=30, verbose_name='Pristatymo būdas')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='delivery_option',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryoption', verbose_name='Pristaytas'),
        ),
    ]
