# Generated by Django 5.1.2 on 2024-10-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_deliveryoption_alter_client_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoption',
            name='delivery_price',
            field=models.FloatField(default=0.0, verbose_name='Pristatymo kaina'),
        ),
    ]
