# Generated by Django 5.1.2 on 2024-10-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_deliveryoption_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='delivery_option',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryoption', verbose_name='Pristaytas'),
        ),
    ]
