# Generated by Django 5.1.2 on 2024-10-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_client_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='delivery_option',
            field=models.CharField(max_length=50, verbose_name='Pristatymo būdas'),
        ),
    ]
