# Generated by Django 5.1.2 on 2024-10-22 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_deliveryoption_delivery_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='roses',
            new_name='flowers',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryoption', verbose_name='Pristaytas'),
        ),
    ]
