# Generated by Django 5.1.2 on 2024-10-22 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_roses_order_flowers_order_delivery_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='order',
            name='decoration_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='roses_qty',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wp_qty',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shop.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.deliveryoption'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='flowers',
        ),
        migrations.CreateModel(
            name='OrderDecoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.decorations')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='decorations',
            field=models.ManyToManyField(related_name='orders', through='shop.OrderDecoration', to='shop.decorations'),
        ),
        migrations.CreateModel(
            name='OrderFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.flowers')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='flowers',
            field=models.ManyToManyField(related_name='orders', through='shop.OrderFlower', to='shop.flowers'),
        ),
    ]
