# Generated by Django 5.1.2 on 2024-10-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
