# Generated by Django 5.1.2 on 2024-10-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_client_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
