# Generated by Django 5.1.2 on 2024-10-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('vykdomas', 'Vykdomas'), ('atsauktas', 'Atsauktas'), ('issiustas', 'Issiustas'), ('ivykdytas', 'Ivykdytas')], default='vykdomas', max_length=20, verbose_name='Order Status'),
        ),
    ]
