# Generated by Django 5.1.2 on 2024-10-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('neapmokėtas', 'Neapmokėtas'), ('apmokėtas', 'Apmokėtas')], default='neapmokėtas', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('vykdomas', 'Vykdomas'), ('atsauktas', 'Atšauktas'), ('issiustas', 'Išsiųstas'), ('ivykdytas', 'Ivykdytas')], default='vykdomas', max_length=20, verbose_name='Order Status'),
        ),
    ]
