# Generated by Django 5.1.2 on 2024-10-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrappingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('remaining', models.FloatField(default=0, verbose_name='Remaining')),
                ('image', models.ImageField(upload_to='wrapping_paper/')),
            ],
        ),
        migrations.DeleteModel(
            name='Materials',
        ),
    ]
