# Generated by Django 5.1.2 on 2024-10-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_wrappingpaper_delete_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='wrapping_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.wrappingpaper'),
        ),
    ]
