# Generated by Django 5.1.2 on 2024-10-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_cartitem_wrapping_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWrappingPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_wrapping_papers', to='shop.order')),
                ('wrapping_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.wrappingpaper')),
            ],
        ),
    ]
