# Generated by Django 5.1.2 on 2024-11-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorations',
            name='cost_to_produce',
            field=models.FloatField(default=1, verbose_name='Cost to produce'),
        ),
        migrations.AddField(
            model_name='flowers',
            name='cost_to_produce',
            field=models.FloatField(default=0.3, verbose_name='Cost to produce'),
        ),
    ]
