# Generated by Django 5.1.2 on 2024-11-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_decorations_cost_to_produce_flowers_cost_to_produce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorations',
            name='cost_to_produce',
        ),
        migrations.AddField(
            model_name='decorations',
            name='cost_to_buy',
            field=models.FloatField(default=1, verbose_name='Cost to buy'),
        ),
    ]
